# -*- coding: utf-8 -*-
"""Büyük semtler için elle yazılmış, sayfaya özel içerik.
Buradaki her kayıt şablondan çıkmaz; bölgeye özgü gerçek bağlamı taşır."""

FLAGSHIP = {
 "bahcesehir": {
  "name": "Bahçeşehir", "district": "Başakşehir", "district_slug": "basaksehir",
  "branch": "bahcesehir", "serum_page": True,
  "covers": ["Bahçeşehir 1. Kısım", "Bahçeşehir 2. Kısım", "Ispartakule", "Boğazköy sınırı", "Hoşdere yönü"],
  "lead": "Bahçeşehir, ekibimizin en yoğun çalıştığı bölgelerden biri — burada sabit bir konumumuz var. Site içi adreslere, blok ve daire tarifiyle doğrudan geliyoruz; güvenlik kaydı için gerekli bilgiyi telefonda alıyoruz ki kapıda vakit kaybetmeyin.",
  "context_title": "Bahçeşehir'de evde sağlık talebi neden bu kadar yüksek?",
  "context": [
   "Bahçeşehir 1. Kısım ve 2. Kısım büyük ölçüde site yerleşimi. Site içinde araçla dolaşmak, blok bulmak ve güvenlikten geçmek dışarıdan gelen bir ekip için zaman kaybı demek. Biz bölgeyi bildiğimiz için bu süreyi baştan hesaba katmıyoruz.",
   "Bölgede çocuklu genç aile nüfusu yoğun. Gece yükselen ateş, mide virüsü ve kusma vakaları en sık aldığımız çağrılar arasında. Ebeveynler çoğu zaman çocuğu gece yarısı arabaya bindirmek yerine ekibi eve çağırmayı tercih ediyor.",
   "Ispartakule ve Hoşdere yönündeki yeni konut alanları hızla doldu; bu bölgelerde en yakın hastane mesafesi hâlâ araçla ciddi bir süre demek. Serum, enjeksiyon ve pansuman gibi hastane gerektirmeyen işlemler için evde çözüm gerçek bir ihtiyaç.",
   "Bahçeşehir Gölet çevresi ve çarşı hattındaki daha eski yerleşimde ise yerleşik yaşlı nüfus var. Burada en sık sonda değişimi, yatak yarası pansumanı ve düzenli B12 enjeksiyonu için çağrılıyoruz.",
  ],
  "extra": ("Site ve rezidanslarda nasıl ilerliyoruz?", [
    "Arama sırasında site adı, blok ve daire numarasını alıyoruz",
    "Güvenlik giriş kaydı için gereken bilgiyi önceden not ediyoruz",
    "Otopark ya da ziyaretçi girişi hangisiyse ona göre yönleniyoruz",
    "Asansörsüz bloklarda malzeme taşımayı hesaba katarak çıkıyoruz",
    "İşlem sonrası tıbbi atık site çöpüne bırakılmıyor, ekiple geri götürülüyor",
  ]),
  "faq": [
   ("Bahçeşehir'de sabit bir yeriniz var mı?", "Evet. Bahçeşehir'de konumumuz var ve bölgedeki çağrıların büyük kısmını buradan karşılıyoruz. Haritadan konumu görebilirsiniz."),
   ("Site içine giriyor musunuz?", "Evet. Güvenlikli sitelerde giriş kaydı için gereken bilgiyi telefonda alıyoruz, kapıda beklemek zorunda kalmıyorsunuz."),
   ("Bahçeşehir 1. Kısım ve 2. Kısım ayrımı sizin için fark eder mi?", "Hizmet açısından fark etmez, ikisine de gidiyoruz. Sadece adres tarifi için hangisi olduğunu belirtmeniz yeterli."),
   ("Ispartakule tarafına da geliyor musunuz?", "Evet, Ispartakule ve Hoşdere yönü de hizmet alanımızın içinde."),
   ("Gece serum için geliyor musunuz?", "Evet, 7/24 çalışıyoruz. Gece saatlerinde de aynı numaradan ulaşabilirsiniz."),
   ("Çocuğuma serum takılabilir mi?", "Çocuklarda uygulama, mutlaka çocuk hekimi değerlendirmesi ve istemi sonrası yapılır. Öncesinde muayene için yönlendirme yaparız."),
  ],
 },
 "hadimkoy": {
  "name": "Hadımköy", "district": "Arnavutköy", "district_slug": None,
  "branch": "bahcesehir", "serum_page": True,
  "covers": ["Hadımköy Mahallesi", "Deliklikaya", "Ömerli", "Bolluca yönü", "OSB ve sanayi bölgesi"],
  "lead": "Hadımköy hem sanayi hem konut bölgesi — ve bu ikisi bizim için farklı iki tip çağrı demek. Gündüz saatlerinde iş yeri ve fabrika kaynaklı yara-pansuman talepleri, akşam ve gece ise ev adreslerinden serum ve enjeksiyon çağrıları alıyoruz. İkisine de aynı hızla gidiyoruz.",
  "context_title": "Hadımköy'de en sık hangi nedenlerle çağrılıyoruz?",
  "context": [
   "Hadımköy, İstanbul'un en büyük sanayi ve lojistik hatlarından birinin üzerinde. Vardiyalı çalışan yoğunluğu yüksek; mesai bitiminde poliklinik kapalı olduğu için pansuman ve enjeksiyon devamı akşam saatlerine kayıyor. 7/24 çalışmamızın en çok işe yaradığı yerlerden biri.",
   "Bölgedeki iş yerlerinden gelen en sık talep, hekim tarafından başlatılmış bir tedavinin devamı: dikiş sonrası pansuman, tetanoz sonrası takip, kesi ve ezik yaralarının düzenli bakımı. Bu işlemler için çalışanın her gün hastaneye gitmesi gerekmiyor.",
   "Deliklikaya, Ömerli ve Bolluca yönündeki konut alanlarında ise yerleşik aile nüfusu var. Buradan gelen çağrılar daha çok çocuklarda ateş-kusma, yaşlılarda sonda ve serum takibi şeklinde.",
   "Hadımköy'ün coğrafyası geniş ve adresler birbirinden uzak. Bu yüzden telefonda konumu net almaya özen gösteriyoruz; yanlış tarif burada 20 dakika değil, çok daha fazla kayıp demek.",
  ],
  "extra": ("İş yeri ve fabrika adreslerinde", [
    "İş yeri hekimi ya da hastane raporunuz varsa fotoğrafını isteriz",
    "Vardiya saatinize göre randevu planlanabilir",
    "Düzenli pansuman gerekiyorsa gün ve saat sabitlenir",
    "Tıbbi atık iş yerinde bırakılmaz, ekiple geri alınır",
    "Toplu talepte önceden arayıp planlama yapmanız işi hızlandırır",
  ]),
  "faq": [
   ("Hadımköy sanayi bölgesine geliyor musunuz?", "Evet. OSB ve çevresindeki iş yeri adreslerine de ev adreslerine de gidiyoruz."),
   ("Vardiya çıkışı geç saatte olacak, sorun olur mu?", "Olmaz. 7/24 çalışıyoruz; gece vardiya çıkışına denk gelen saatlerde de geliyoruz."),
   ("Her gün pansuman gerekiyor, düzenli gelebilir misiniz?", "Evet. Hekimin belirlediği aralığa göre gün ve saat sabitlenir, aynı ekiple devam edilmeye çalışılır."),
   ("Deliklikaya ve Ömerli'ye de geliyor musunuz?", "Evet, Hadımköy çevresindeki bu yerleşimler de hizmet alanımızın içinde."),
   ("Hadımköy'e ne kadar sürede gelirsiniz?", "Bölge geniş olduğu için süre adresin tam yerine göre değişir. Aradığınızda size gerçekçi bir varış saati söyleriz, tahminde bulunmayız."),
   ("İş kazası sonrası ilk müdahale yapıyor musunuz?", "Acil ve ciddi yaralanmalarda 112 aranmalıdır. Biz hekim değerlendirmesi yapılmış yaraların takibini ve pansumanını üstleniriz."),
  ],
 },
 "esenkent": {
  "name": "Esenkent", "district": "Esenyurt", "district_slug": "esenyurt",
  "branch": "esenyurt", "serum_page": True,
  "covers": ["Esenkent Mahallesi", "Yeşilkent sınırı", "Kıraç yönü", "Bahçeşehir çıkışı"],
  "lead": "Esenkent, Esenyurt'un batı ucunda — Kıraç, Yeşilkent ve Bahçeşehir üçgeninin tam ortasında. Ekiplerimizin en kısa sürede ulaştığı bölgelerden biri, çünkü hem Esenyurt hem Bahçeşehir konumumuz buraya yakın.",
  "context_title": "Esenkent'te evde sağlık neden tercih ediliyor?",
  "context": [
   "Esenkent büyük ölçüde toplu konut ve site yerleşimi. Blok sayısı fazla, adres tarifi karışık olabiliyor; bölgeyi bildiğimiz için doğru bloğu bulmak bizde vakit almıyor.",
   "Mahallede genç çalışan nüfus yoğun. En sık gelen çağrı, hafta içi mesai bitiminde ya da hafta sonu hastane kalabalığına girmek istemeyen kişilerden geliyor: serum, enjeksiyon ve tahlil öncesi hazırlık.",
   "Esenkent'ten hastaneye ulaşım, trafik saatinde ciddi bir yük. Bulantı-kusma ya da migren atağı gibi durumlarda arabaya binmek başlı başına bir eziyet; bu vakalarda evde uygulama gerçek bir fark yaratıyor.",
   "Bölgede yaşlı ebeveyniyle oturan aile sayısı da az değil. Düzenli B12 iğnesi, sonda değişimi ve yatak yarası pansumanı için haftalık düzende geldiğimiz adresler var.",
  ],
  "extra": None,
  "faq": [
   ("Esenkent'e ne kadar sürede gelirsiniz?", "Esenkent, Esenyurt ve Bahçeşehir konumlarımızın ikisine de yakın. Yine de kesin süreyi o anki ekip durumuna göre telefonda söyleriz."),
   ("Site içine giriyor musunuz?", "Evet. Blok ve daire bilgisini telefonda alıp güvenlik kaydını hızlandırıyoruz."),
   ("Gece de geliyor musunuz?", "Evet, Esenkent dahil tüm hizmet bölgemizde 7/24 çalışıyoruz."),
   ("Yeşilkent ve Kıraç tarafına da geliyor musunuz?", "Evet, ikisi de hizmet alanımızın içinde."),
   ("Serum için reçete şart mı?", "Evet. Serum ve içine eklenen ilaçlar hekim istemi olmadan uygulanmaz."),
  ],
 },
 "kirac": {
  "name": "Kıraç", "district": "Esenyurt", "district_slug": "esenyurt",
  "branch": "esenyurt", "serum_page": True,
  "covers": ["Fatih", "Namık Kemal", "İnönü", "Mehterçeşme yönü", "Kıraç sanayi hattı"],
  "lead": "Kıraç, Esenyurt'un batısında konut ve sanayinin iç içe geçtiği bir bölge. Gündüz iş yeri, akşam ev adresi — günün saatine göre çağrının tipi değişiyor. Esenyurt konumumuz Kıraç'a en yakın noktalardan biri.",
  "context_title": "Kıraç'ta öne çıkan durumlar",
  "context": [
   "Kıraç'ta sanayi ve atölye yoğunluğu yüksek. Kesi, ezik ve yanık sonrası hekim müdahalesi yapılmış yaraların düzenli pansumanı en sık aldığımız taleplerden biri.",
   "Bölgede kiracı ve genç çalışan nüfusu fazla. Bu grupta en çok grip, yüksek ateş ve gıda zehirlenmesi kaynaklı serum çağrısı alıyoruz — çoğu, ertesi gün işe gidebilmek için akşam saatinde arıyor.",
   "Kıraç tek bir mahalle değil; Fatih, Namık Kemal ve çevresindeki mahalleleri kapsayan bir bölge. Adres tarifinde mahalle adını da almamız, doğru sokağa gitmemizi hızlandırıyor.",
   "Beylikdüzü ve Esenyurt merkez arasındaki hat üzerinde olması, ekiplerimizin gün içinde buradan sık geçmesi demek. Yoğun saatlerde bile Kıraç için makul bir varış süresi verebiliyoruz.",
  ],
  "extra": None,
  "faq": [
   ("Kıraç hangi ilçeye bağlı?", "Kıraç, Esenyurt ilçesi sınırları içindedir. Fatih, Namık Kemal ve çevre mahalleleri kapsar."),
   ("İş yerine gelir misiniz?", "Evet. Atölye ve fabrika adreslerine de gidiyoruz."),
   ("Gece serum takılır mı?", "Evet, 7/24 hizmet veriyoruz."),
   ("Pansumanı her gün yapabilir misiniz?", "Hekiminizin belirlediği aralığa göre düzenli olarak gelebiliriz."),
   ("Malzemeyi biz mi alacağız?", "Reçeteli ilaç ve özel yara örtüsü size aittir; standart uygulama malzemesi ekiple gelir."),
  ],
 },
 "kumburgaz": {
  "name": "Kumburgaz", "district": "Büyükçekmece", "district_slug": "buyukcekmece",
  "branch": "beylikduzu", "serum_page": True,
  "covers": ["Kumburgaz Mahallesi", "Celaliye", "Kamiloba", "Mimaroba yönü", "Sahil bandı"],
  "lead": "Kumburgaz, Büyükçekmece'nin sahil hattında yerleşik nüfusla yazlık nüfusun bir arada olduğu bir bölge. Yaz aylarında nüfus artıyor, kış aylarında ise yaşlı yerleşik nüfusun düzenli bakım ihtiyacı öne çıkıyor.",
  "context_title": "Kumburgaz'da mevsime göre değişen ihtiyaçlar",
  "context": [
   "Yaz döneminde Kumburgaz'da en sık aldığımız çağrılar güneş çarpması, sıvı kaybı, gıda zehirlenmesi ve böcek sokması sonrası alerjik tablolar. Bu vakaların çoğu hastane gerektirmiyor, hekim yönlendirmesiyle evde çözülebiliyor.",
   "Kış aylarında ise bölgede kalan yerleşik nüfus ağırlıklı olarak yaşlı. Sonda değişimi, yatak yarası pansumanı, düzenli enjeksiyon ve tansiyon-şeker takibi bu dönemin ana talepleri.",
   "Kumburgaz sahil bandı boyunca uzanan bir yerleşim; site, apart ve müstakil ev karışık. Adres tarifi burada gerçekten önemli, bu yüzden telefonda konum paylaşımını sık öneriyoruz.",
   "Bölgeden merkez hastanelere ulaşım özellikle yaz trafiğinde uzuyor. Serum ve enjeksiyon gibi işlemler için yola çıkmak yerine ekibi çağırmak çoğu zaman daha hızlı.",
  ],
  "extra": None,
  "faq": [
   ("Yazlık siteye de geliyor musunuz?", "Evet. Kumburgaz sahil hattındaki site ve apart adreslerine geliyoruz."),
   ("Kumburgaz'a gece geliyor musunuz?", "Evet, 7/24 çalışıyoruz."),
   ("Celaliye ve Kamiloba'ya da geliyor musunuz?", "Evet, Kumburgaz çevresindeki bu mahalleler de hizmet alanımızın içinde."),
   ("Yaşlı hastam için düzenli bakım planlanabilir mi?", "Evet. Hekiminizin planına göre haftalık ya da aylık düzende gelebiliriz."),
   ("Adres tarifi zor, ne yapmalıyım?", "WhatsApp üzerinden konum atmanız yeterli; ekip doğrudan oraya yönlendirilir."),
  ],
 },
 "bogazkoy": {
  "name": "Boğazköy", "district": "Arnavutköy", "district_slug": None,
  "branch": "bahcesehir", "serum_page": False,
  "covers": ["Boğazköy İstiklal", "Boğazköy Fatih", "Taşoluk yönü", "Bahçeşehir sınırı"],
  "lead": "Boğazköy, Bahçeşehir'e komşu olduğu için ekiplerimizin gün içinde sık geçtiği bir bölge. Toplu konut alanları ve yerleşik mahalle dokusu bir arada; her iki yapıda da düzenli çağrı alıyoruz.",
  "context_title": "Boğazköy'de en sık gelen talepler",
  "context": [
   "Boğazköy İstiklal ve Fatih mahallelerindeki toplu konut alanlarında genç aile nüfusu yoğun. Çocuklarda ateş, kusma ve ishal kaynaklı gece çağrıları listenin başında.",
   "Bahçeşehir konumumuza yakınlığı sayesinde bu bölgeye ulaşmamız kısa sürüyor; özellikle gece saatlerinde bu fark hissediliyor.",
   "Bölgede yerleşik yaşlı nüfusun düzenli ihtiyaçları da var: sonda değişimi, B12 enjeksiyonu, tansiyon ve şeker takibi için haftalık gittiğimiz adresler bulunuyor.",
   "Taşoluk yönündeki yeni yerleşim alanlarında hastane mesafesi hâlâ uzun. Hekim istemi olan serum ve enjeksiyon işlemleri için evde uygulama pratik bir çözüm.",
  ],
  "extra": None,
  "faq": [
   ("Boğazköy hangi ilçeye bağlı?", "Boğazköy, Arnavutköy ilçesine bağlıdır; İstiklal ve Fatih mahallelerini kapsar."),
   ("Bahçeşehir'den mi geliyorsunuz?", "Evet, Boğazköy çağrılarını çoğunlukla Bahçeşehir konumumuzdan karşılıyoruz."),
   ("Gece hizmet var mı?", "Evet, 7/24 çalışıyoruz."),
   ("Taşoluk tarafına da geliyor musunuz?", "Evet, Taşoluk yönü de hizmet alanımızın içinde."),
  ],
 },
 "beykent": {
  "name": "Beykent", "district": "Büyükçekmece", "district_slug": "buyukcekmece",
  "branch": "beylikduzu", "serum_page": True,
  "covers": ["Pınartepe", "Beykent siteleri", "Beylikdüzü sınırı", "Cumhuriyet yönü"],
  "lead": "Beykent, Beylikdüzü ile Büyükçekmece'nin birleştiği noktada, site yoğunluğu yüksek bir bölge. Öğrenci nüfusu ve genç aileler bir arada; ikisinin de talep profili farklı.",
  "context_title": "Beykent'te öne çıkan başlıklar",
  "context": [
   "Bölgede üniversite kaynaklı öğrenci nüfusu var. Evden uzakta kalan öğrencilerden gelen çağrılar çoğunlukla yüksek ateş, grip ve gıda zehirlenmesi kaynaklı; ailesi başka şehirde olan kişiler için evde uygulama ciddi bir rahatlama.",
   "Beykent ve çevresindeki siteler yoğun; blok ve kapı numarası tarifini telefonda net almamız, kapıda dolaşma süresini sıfırlıyor.",
   "Beylikdüzü konumumuz Beykent'e çok yakın. Bu bölge için verdiğimiz varış süreleri hizmet alanımızın en kısaları arasında.",
   "Sınavlar ve iş yoğunluğu dönemlerinde halsizlik ve vitamin desteği talebi artıyor; ancak bu uygulamaların da hekim değerlendirmesi ve istemi ile yapıldığını her seferinde belirtiyoruz.",
  ],
  "extra": None,
  "faq": [
   ("Beykent hangi ilçede?", "Beykent, büyük ölçüde Büyükçekmece ilçesi Pınartepe bölgesinde yer alır ve Beylikdüzü ile sınır komşusudur."),
   ("Öğrenci evine geliyor musunuz?", "Evet. Ev, yurt ya da apart fark etmez; adres verdiğiniz yere geliyoruz."),
   ("Yalnız yaşıyorum, uygulama sırasında yanımda kalıyor musunuz?", "Evet. Serum bitene kadar hemşire evde kalır."),
   ("Ne kadar sürede gelirsiniz?", "Beykent, Beylikdüzü konumumuza yakın. Yine de net süreyi telefonda söyleriz."),
  ],
 },
 "yakuplu": {
  "name": "Yakuplu", "district": "Beylikdüzü", "district_slug": "beylikduzu",
  "branch": "beylikduzu", "serum_page": True,
  "covers": ["Yakuplu Mahallesi", "Marmara yönü", "Sahil hattı", "Beylikdüzü merkez"],
  "lead": "Yakuplu, Beylikdüzü'nün en kalabalık mahallelerinden biri ve Beylikdüzü konumumuzun hemen yanı başında. Bölgedeki çağrılara en hızlı ulaştığımız yerlerden biri diyebiliriz.",
  "context_title": "Yakuplu'da neler oluyor?",
  "context": [
   "Yakuplu'da hem eski yerleşim hem yeni site dokusu bir arada. Bu, çok farklı yaş gruplarından çağrı almamız demek: bebekli ailelerden yatağa bağımlı hastalara kadar.",
   "Mahalledeki en sık düzenli hizmetimiz, kronik hastalarda haftalık enjeksiyon ve pansuman takibi. Aynı adrese aynı ekibin gitmesine özen gösteriyoruz.",
   "Beylikdüzü konumumuz burada olduğu için gece çağrılarında Yakuplu için verebildiğimiz süreler kısa. Özellikle ateş ve kusma vakalarında bu fark önemli.",
   "Bölgede sağlık kuruluşuna yakınlık avantajı olsa da, kalabalık poliklinik saatlerinde beklemek istemeyen kişiler serum ve enjeksiyon için bizi tercih ediyor.",
  ],
  "extra": None,
  "faq": [
   ("Yakuplu'ya ne kadar sürede gelirsiniz?", "Beylikdüzü konumumuz Yakuplu'ya çok yakın; yine de kesin süreyi arama anında söyleriz."),
   ("Düzenli hasta bakımı planlıyor musunuz?", "Evet, hekim planına göre haftalık ya da aylık düzen kurulabilir."),
   ("Gece geliyor musunuz?", "Evet, 7/24 çalışıyoruz."),
   ("Yaşlı hastam yatağa bağımlı, gelebilir misiniz?", "Evet. Yatağa bağımlı hastalarda sonda, pansuman ve enjeksiyon hizmetleri evde verilir."),
  ],
 },
 "haramidere": {
  "name": "Haramidere", "district": "Esenyurt", "district_slug": "esenyurt",
  "branch": "esenyurt", "serum_page": True,
  "covers": ["Güzelyurt", "Sanayi bölgesi", "Avcılar sınırı", "Ambarlı yönü"],
  "lead": "Haramidere, Esenyurt ile Avcılar arasındaki sanayi ve konut hattı. Gündüz iş yeri kaynaklı yara-pansuman, akşam ev adreslerinden serum ve enjeksiyon çağrıları alıyoruz.",
  "context_title": "Haramidere'de tipik çağrılar",
  "context": [
   "Bölgedeki sanayi sitesi ve atölyeler nedeniyle kesi, ezik ve yanık sonrası pansuman takibi burada diğer mahallelere göre daha yoğun.",
   "Mesai saatleri dışında poliklinik bulmak zor. Hekim tarafından başlatılmış bir tedavinin devamı için akşam ve gece saatlerinde en çok arandığımız bölgelerden biri.",
   "Konut tarafında genç çalışan nüfus ağırlıkta; grip, yüksek ateş ve mide rahatsızlığı kaynaklı serum çağrıları listenin başında.",
   "Haramidere, E-5 hattı üzerinde olduğu için ekiplerimizin gün içinde sık geçtiği bir güzergâh; bu da makul varış süreleri anlamına geliyor.",
  ],
  "extra": None,
  "faq": [
   ("Haramidere hangi ilçede?", "Haramidere, Esenyurt ile Avcılar sınırında yer alan bir bölgedir; her iki tarafa da hizmet veriyoruz."),
   ("İş yerine gelir misiniz?", "Evet, sanayi ve atölye adreslerine de gidiyoruz."),
   ("Gece hizmet var mı?", "Evet, 7/24."),
   ("Düzenli pansuman yapabilir misiniz?", "Evet, hekiminizin belirlediği aralıkla."),
  ],
 },
 "ispartakule": {
  "name": "Ispartakule", "district": "Başakşehir", "district_slug": "basaksehir",
  "branch": "bahcesehir", "serum_page": False,
  "covers": ["Bahçeşehir 2. Kısım sınırı", "Ispartakule siteleri", "Hoşdere yönü"],
  "lead": "Ispartakule, son yıllarda hızla dolan yeni site bölgesi. Bahçeşehir konumumuza komşu olduğu için ulaşımımız kısa; bölgedeki blokları ve giriş düzenini biliyoruz.",
  "context_title": "Ispartakule'de dikkat ettiğimiz noktalar",
  "context": [
   "Bölge neredeyse tamamen yeni site yerleşimi. Blok isimleri ve giriş kapıları benzer olduğu için adres bilgisini telefonda ayrıntılı alıyoruz.",
   "Genç aile nüfusu yoğun; çocuklarda ateş, kusma ve ishal kaynaklı gece çağrıları en sık gelen talep.",
   "Bölgeden hastaneye ulaşım araçla belirli bir süre alıyor. Serum ve enjeksiyon gibi işlemler için evde uygulama zaman kazandırıyor.",
   "Bahçeşehir konumumuz komşu olduğundan, gece saatlerinde Ispartakule için verdiğimiz süreler kısa kalıyor.",
  ],
  "extra": None,
  "faq": [
   ("Ispartakule hangi ilçeye bağlı?", "Ispartakule, Başakşehir ilçesi sınırları içinde, Bahçeşehir'e komşu bir bölgedir."),
   ("Site içine giriyor musunuz?", "Evet. Blok ve daire bilgisini önceden alıyoruz."),
   ("Gece geliyor musunuz?", "Evet, 7/24 çalışıyoruz."),
  ],
 },
 "mimarsinan": {
  "name": "Mimarsinan", "district": "Büyükçekmece", "district_slug": "buyukcekmece",
  "branch": "beylikduzu", "serum_page": False,
  "covers": ["Mimarsinan Mahallesi", "Mimaroba", "Sinanoba", "Sahil hattı"],
  "lead": "Mimarsinan ve çevresindeki Mimaroba-Sinanoba hattı, Büyükçekmece'nin sahil bandındaki yerleşik nüfusun yoğun olduğu bölge. Düzenli hasta bakımı taleplerinin en çok geldiği yerlerden biri.",
  "context_title": "Mimarsinan bölgesinde öne çıkanlar",
  "context": [
   "Bölgede yerleşik ve yaşça büyük nüfus oranı yüksek. Sonda değişimi, yatak yarası pansumanı ve düzenli enjeksiyon burada en sık verdiğimiz hizmetler.",
   "Mimaroba ve Sinanoba tarafındaki site yerleşiminde ise genç aile çağrıları ağırlıkta: ateş, kusma ve grip kaynaklı serum talepleri.",
   "Sahil hattı boyunca uzanan yerleşim nedeniyle adresler birbirinden uzak olabiliyor; konum paylaşımı burada gerçekten işe yarıyor.",
   "Beylikdüzü konumumuz bu hatta yakın; sahil yolu üzerinden ulaşım makul sürede tamamlanıyor.",
  ],
  "extra": None,
  "faq": [
   ("Mimaroba ve Sinanoba'ya da geliyor musunuz?", "Evet, üç bölge de hizmet alanımızın içinde."),
   ("Yaşlı hastam için düzenli bakım kurulabilir mi?", "Evet, hekim planına göre haftalık düzen kurulur."),
   ("Gece hizmet var mı?", "Evet, 7/24 çalışıyoruz."),
  ],
 },
 "ambarli": {
  "name": "Ambarlı", "district": "Avcılar", "district_slug": "avcilar",
  "branch": "beylikduzu", "serum_page": False,
  "covers": ["Ambarlı Mahallesi", "Liman bölgesi", "Haramidere sınırı", "Denizköşkler yönü"],
  "lead": "Ambarlı, Avcılar'ın liman ve sanayi hattındaki mahallesi. Hem iş yeri hem konut adreslerinden çağrı alıyoruz; iki tarafın da ihtiyacı farklı.",
  "context_title": "Ambarlı'da tipik durumlar",
  "context": [
   "Liman ve depo bölgesindeki iş yerlerinden gelen talepler ağırlıklı olarak pansuman ve hekim tarafından başlatılmış tedavinin devamı.",
   "Konut tarafında ise yerleşik aile nüfusu var; ateş, kusma ve grip kaynaklı serum çağrıları ile yaşlılarda düzenli enjeksiyon talepleri öne çıkıyor.",
   "Vardiyalı çalışan yoğunluğu nedeniyle akşam ve gece saatlerindeki çağrı oranı bölgede yüksek.",
   "E-5 hattına yakınlığı sayesinde ekiplerimizin ulaşımı makul sürede tamamlanıyor.",
  ],
  "extra": None,
  "faq": [
   ("Liman bölgesindeki iş yerlerine geliyor musunuz?", "Evet, iş yeri adreslerine de gidiyoruz."),
   ("Gece hizmet var mı?", "Evet, 7/24 çalışıyoruz."),
   ("Düzenli pansuman planlanabilir mi?", "Evet, hekiminizin belirlediği aralıkla geliriz."),
  ],
 },
}
